export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const GET_CINEMA = 'GET_CINEMA';
export const GET_CINEMAS = 'GET_CINEMAS';
export const ADD_CINEMA = 'ADD_CINEMA';
export const DELETE_CINEMA = 'DELETE_CINEMA';
export const CINEMAS_LOADING = 'CINEMAS_LOADING';
export const CLEAN_CINEMAS = 'CLEAN_CINEMAS';
export const ADD_CINEMA_FAIL = 'ADD_CINEMA_FAIL';

export const GET_MOVIES = 'GET_MOVIES';
export const GET_MOVIE_TIMES_FOR_CINEMA = 'GET_MOVIE_TIMES_FOR_CINEMA';
export const GET_MOVIE = 'GET_MOVIE';
export const GET_MOVIE_TIMES = 'GET_MOVIE_TIMES';
export const CLEAN_MOVIES = 'CLEAN_MOVIES';
export const DELETE_MOVIE = 'DELETE_MOVIE';

export const EDIT_MOVIE = 'EDIT_MOVIE';
export const EDIT_MOVIE_FAIL = 'EDIT_MOVIE_FAIL';
export const LOAD_MOVIE = 'LOAD_MOVIE';

export const ADD_MOVIES = 'ADD_MOVIES';
export const MOVIES_LOADING = 'MOVIES_LOADING';
export const MOVIE_TIMES_LOADING = 'MOVIE_TIMES_LOADING';
export const ADD_MOVIES_FAIL = 'ADD_MOVIES_FAIL';

export const GET_SIT_TYPES = 'GET_SIT_TYPES';
export const GET_SIT_TYPE = 'GET_SIT_TYPE';
export const ADD_SIT_TYPE = 'ADD_SIT_TYPE';
export const ADD_SIT_TYPE_FAIL = 'ADD_SIT_TYPE_FAIL';
export const EDIT_SIT_TYPE = 'EDIT_SIT_TYPE';
export const DELETE_SIT_TYPE = 'DELETE_SIT_TYPE';
export const SIT_TYPE_LOADING = 'SIT_TYPE_LOADING';

export const GET_MOVIE_TIME = 'GET_MOVIE_TIME';
export const ADD_MOVIE_TIME = 'ADD_MOVIE_TIME';
export const ADD_MOVIE_TIME_FAIL = 'ADD_MOVIE_TIME_FAIL';
export const EDIT_MOVIE_TIME = 'EDIT_MOVIE_TIME';
export const DELETE_MOVIE_TIME = 'DELETE_MOVIE_TIME';
export const MOVIE_TIME_LOADING = 'MOVIE_TIME_LOADING';
export const GET_CINEMAS_WITH_HALLS = 'GET_CINEMAS_WITH_HALLS';
export const GET_MOVIES_FOR_MOVIE_TIMES = 'GET_MOVIES_FOR_MOVIE_TIMES';
export const GET_CINEMA_HALLS_FOR_MOVIE_TIMES = 'GET_CINEMA_HALLS_FOR_MOVIE_TIMES';
export const GET_CINEMAS_FOR_MOVIE_TIMES = 'GET_CINEMAS_FOR_MOVIE_TIMES';
export const GET_SITS_TYPES_FOR_MOVIE_TIMES = 'GET_SITS_TYPES_FOR_MOVIE_TIMES';

export const ADD_EXTRAS = 'ADD_EXTRAS';
export const ADD_EXTRAS_FAIL = 'ADD_EXTRAS_FAIL';
