export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const GET_CINEMA = 'GET_CINEMA';
export const GET_CINEMAS = 'GET_CINEMAS';
export const ADD_CINEMA = 'ADD_CINEMA';
export const DELETE_CINEMA = 'DELETE_CINEMA';
export const CINEMAS_LOADING = 'CINEMAS_LOADING';
export const CLEAN_CINEMAS = 'CLEAN_CINEMAS';

export const GET_MOVIES = 'GET_MOVIES';
export const GET_MOVIE_TIMES_FOR_CINEMA = 'GET_MOVIE_TIMES_FOR_CINEMA';
export const GET_MOVIE = 'GET_MOVIE';
export const GET_MOVIE_TIMES = 'GET_MOVIE_TIMES';
export const CLEAN_MOVIES = 'CLEAN_MOVIES';
export const DELETE_MOVIE = 'DELETE_MOVIE';

export const EDIT_MOVIE = 'EDIT_MOVIE';
export const EDIT_MOVIE_FAIL = 'EDIT_MOVIE_FAIL';
export const LOAD_MOVIE = 'LOAD_MOVIE';

export const ADD_MOVIES = 'ADD_MOVIES';
export const MOVIES_LOADING = 'MOVIES_LOADING';
export const MOVIE_TIMES_LOADING = 'MOVIE_TIMES_LOADING';
export const ADD_MOVIES_FAIL = 'ADD_MOVIES_FAIL';
